name: SonarQube Analysis with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:community:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -s http://localhost:9000/api/system/health | grep -q UP"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set up JDK 17.0.9
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - name: Install Maven 3.9.6
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvzf apache-maven-3.9.6-bin.tar.gz
          sudo mv apache-maven-3.9.6 /opt/maven
          echo "export PATH=/opt/maven/bin:\$PATH" >> $GITHUB_ENV

      - name: Wait for SonarQube to be ready
        run: sleep 60

      - name: SonarQube Scan
        working-directory: ./repo/HelloWorldApp
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_LOGIN: admin
          SONAR_PASSWORD: admin
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=YourProjectKey \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN \
          -Dsonar.password=$SONAR_PASSWORD
