name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ./repo  # Ensure correct path

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

  install-maven:
    name: Install Maven
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ./repo  # Ensure correct path

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Verify Maven Installation
        run: mvn -v

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: install-maven
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ./repo  # Ensure correct path

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Files (Debug)
        run: ls -al ./repo  # Confirm checkout

      - name: SonarCloud Scan
        working-directory: ./repo  # Specify correct working directory
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=YourProjectKey \
          -Dsonar.organization=YourSonarCloudOrganization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: sonar-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ./repo  # Ensure correct path

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build with Maven
        working-directory: ./repo  # Specify correct working directory
        run: mvn clean install
