name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set up JDK 17.0.9
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - name: Verify Java Version
        run: java -version

      - name: Verify Directory Contents
        run: |
          pwd
          ls -al
          ls -al ./repo
          find ./repo -name "pom.xml"

  install-maven:
    name: Install Maven 3.9.6
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Install Maven 3.9.6
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvzf apache-maven-3.9.6-bin.tar.gz
          sudo mv apache-maven-3.9.6 /opt/maven

      - name: Update PATH to Use Maven 3.9.6
        run: echo "export PATH=/opt/maven/bin:\$PATH" >> $GITHUB_ENV

      - name: Verify Maven Installation
        run: mvn -v

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: install-maven
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set up JDK 17.0.9
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - name: SonarCloud Scan
        working-directory: ./repo/HelloWorldApp
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=YourProjectKey \
          -Dsonar.organization=YourSonarCloudOrganization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: sonar-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set up JDK 17.0.9
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - name: Verify Directory Contents
        run: |
          pwd
          ls -al ./repo
          find ./repo -name "pom.xml"

      - name: Build with Maven
        working-directory: ./repo/HelloWorldApp
        run: mvn clean install
